### ISSUE TITLE
[BUG] Nav bar button.

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/Blog_Website#100]
### Describe the bug
This bug occurs in PC only and it's quite bugging me. It only shows up after following a few steps below. It appears on the top right corner of the screen.

### To Reproduce

1. Go to 'inspect mode'
2. Switch mobile view
3. Click on the 'navigation bar'
4. Don't close it
5. Switch switch back to laptop view/ close inspect mode
6. See error.

### Expected behavior
It should should disappear by it self.

<img width="960" alt="image" src="https://github.com/Kritika30032002/Blog_Website/assets/108126089/a3512eb2-fb50-4742-a8ca-996d7a24f3df">

**Comment by Kritika30032002** [comment]
fix the whole navbar under 1 issue
