### ISSUE TITLE
[Enhancement] Better home button design in error page.

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/Blog_Website#104]
The button looks very bad after new upgrade in error file. so i think the button also needs a upgrade.
<img width="860" alt="image" src="https://github.com/Kritika30032002/Blog_Website/assets/108126089/97d3d448-618a-4528-99e9-72ee61ccb126">

inspiration's 
![image](https://github.com/Kritika30032002/Blog_Website/assets/108126089/b2e2089c-7d7f-4ae1-af73-cd305aa6a228)

**Comment by Yash-Ainapure** [comment]
Heyy @Kritika30032002 , Could you assign me this issue as i think this shouldn't take this kuch time to complete.
