### ISSUE TITLE
Improve blog detail page by making it more descriptive

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Blog_Website#107]

**Comment by timmySpark** [comment]
@Kritika30032002 can this task be assigned to me?

**Comment by Kritika30032002** [comment]
improve its design and the content

**Comment by timmySpark** [comment]
Hi @Kritika30032002 , I already improved the designs
The Screenshots of the new designs are below this message , can I go ahead and make a pr or you need some other details to be present that's not included at the moment

![Screenshot 2024-03-18 at 20 15 29](https://github.com/Kritika30032002/Blog_Website/assets/84716345/531f5d59-c888-4f91-9e7d-24d660a8b699)
![Screenshot 2024-03-18 at 20 16 40](https://github.com/Kritika30032002/Blog_Website/assets/84716345/855c593d-d98f-41e8-889a-6b9ea33e8b3c)

**Comment by Kritika30032002** [comment]
design of culinary adventures can be improved like increasing font size so that everyone is able to read it and a single image should not whole screen.

you can refer to different websites and see their blog pages.

**Comment by timmySpark** [comment]
@Kritika30032002 , the screenshot for culinary adventures in a 50% zoom so the font is fine, also with websites like medium, they do have more images in their blogs but I think it depends on the person writing the blog to decide to add more images or not.

**Comment by Kritika30032002** [comment]
I am not saying to add multiple images
 image size should be much smaller, it should not occupy whole screen

**Comment by timmySpark** [comment]
okay, I understand better now
