### ISSUE TITLE
Update gitignore file

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Blog_Website#113]

**Comment by praptisharma28** [comment]
Assign me @Kritika30032002

**Comment by hiCXK** [comment]
Updated the .gitignore file to this: 

node_modules/
.env
.env.example

logs/
*.log

pids/
*.pid
*.seed
*.pid.lock

lib/
bin/
build/

data/
mongod.lock

*.ejs

.vscode/
.idea/
*.sublime*
*.swp
*.swo
*.swn
*.bak
*.orig

favicon.ico

.DS_Store

Thumbs.db



Is it fine?

**Comment by praptisharma28** [comment]
sure @Kritika30032002 assign me.

**Comment by praptisharma28** [comment]
https://github.com/Kritika30032002/Blog_Website/pull/116 
Have a look @Kritika30032002 , you made it very easy for me to do, thanks. Also please don't forget to add the iwoc24 and difficulty level and close the issue too!
