### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors

### ISSUE THREAD

**Issue by praptisharma28** [Kritika30032002/Blog_Website#115]
Description:
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

Proposed Changes:
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Comment by Kritika30032002** [comment]
good issue

**Comment by praptisharma28** [comment]
Hey @Kritika30032002 , thanks for assigning. I will add around 2-3 files and will update github token to see the result. Please assign me this under "hard" if you can cause there are no workflows added in your repo & I need to add them from scratch. I will add for Pull request, bug etc.
