### ISSUE TITLE
[Bug]: Website Layout is not responsive

### ISSUE THREAD

**Issue by jiveshkalra** [Kritika30032002/Blog_Website#137]
### What happened?

The website layout is not responsive and doesnt scale to smaller screens and is not usable for mobile phones 
Screenshots -> 
![image](https://github.com/Kritika30032002/Blog_Website/assets/127482713/bf51d3c3-3c08-423f-98b7-23f8f6aa3f82)

### What browsers are you seeing the problem on?
 Brave -> Chromium 

- [X] I agree to follow this project's Code of Conduct

**Comment by Ashmita-15** [comment]
Working on a lot of projects as a frontend developer, i can easily do this. can you please assign this to me after labelling it for GSSOC'24 EXTD :)
