### ISSUE TITLE
[Feature] Improper Password Handling

### ISSUE THREAD

**Issue by jiveshkalra** [Kritika30032002/Blog_Website#139]
### Describe the feature you'd like to request

When someone tries to sign up with a password that doesnt meet the criteria , the form gets submitted and we are redirected to a very messy page where we are said to register once again
![image](https://github.com/Kritika30032002/Blog_Website/assets/127482713/8db417a8-8359-450c-93d0-f66f78c3d35a)

### Describe the solution you'd like

Instead of checking for the password requriements in the backend ,we can make it check for all the password checking in the frontend itself so that the user has a smoother experience.

**Comment by jiveshkalra** [comment]
Alright sure! I will complete other issues asap

**Comment by jinx-vi-0** [comment]
@Kritika30032002 can you please assign this issue to me.

**Comment by jiveshkalra** [comment]
hey sorry @jinx-vi-0 mate i am already onto it, i will be making the necessary commits asap
