### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by payalgupta25** [Kritika30032002/Blog_Website#150]
### Describe the feature you'd like to request

<h2>There should be a footer holding quick links , social media handles of website , logo  </h2>
<hr>
<h1>What can I do </h1>
<ul>
<li>I can design a responsive footer</li>
<li>Holding all important links for quick access , logo and social media accounts</li>
<li>The footer would be matching the color palette of your website</li>
</ul>

Code of Conduct
✅ I agree to follow this project's Code of Conduct

### Describe the solution you'd like

I can design a responsive footer
Holding all important links for quick access , logo and social media accounts
The footer would be matching the color palette of your website

**Comment by Kritika30032002** [comment]
it already has social media handles
