### ISSUE TITLE
no ui interface

### ISSUE THREAD

**Issue by archanasuresh03** [Kritika30032002/Blog_Website#159]
### Describe the feature you'd like to request

why are you disabling compose options?how could we express our thoughts?

### Describe the solution you'd like

plz do enable for our use

**Comment by archanasuresh03** [comment]
Could you recover it.do it to sllow compose our blogs &thoughts.

**Comment by ar1701** [comment]
Hey @archanasuresh03 , i would like to contribute in this. Can u provide more details on and Assign it to me ?

**Comment by Kritika30032002** [comment]
it is for writing and reading blogs and not sharing thoughts
