### ISSUE TITLE
[Feature] <title>Add Footer with Useful Links and Information

### ISSUE THREAD

**Issue by GitWizzz** [Kritika30032002/Blog_Website#169]
### Describe the feature you'd like to request

The system currently lacks a footer, which makes it less user-friendly and visually incomplete. Users don't have quick access to important links, contact information, or other helpful resources when navigating the site.

### Describe the solution you'd like

I would like to add a footer section to the system that includes key information and useful links. The footer should contain:

Quick links to important pages (Home, About Us, Contact, FAQ)
Contact details (email, phone number)
Copyright information
Social media links (optional)

**Comment by Kritika30032002** [comment]
after issue #168 completion

**Comment by GitWizzz** [comment]
it would be great if it resolve quickly
