### ISSUE TITLE
[Bug]: Sign In and Sign Up pages are not working correctly

### ISSUE THREAD

**Issue by akankshagoel28** [Kritika30032002/Blog_Website#175]
### Contact Details

goelakanksha7379@gmail.com

### What happened?

The sign in pages are accepting random and unregistered emails. There is no verification email sent to the email mentioned during the sign up. Even if there is any error in sign in the user is not informed directly, instead he is being redirected to this page. Image attached below:
<img width="1406" alt="Screenshot 2024-10-03 at 6 58 56 PM" src="https://github.com/user-attachments/assets/da1fdbb0-7652-4ba4-8dcb-a480599ae964">
 i will be adding the correct verifications for the sign in and sign up pages and resolve the issues.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pavitra-s-Workspace** [comment]
I'm interested to contribute. please assign me..
