### ISSUE TITLE
[Bug]: Blog Content Not Visible in Dark Theme

### ISSUE THREAD

**Issue by rudrapratap63** [Kritika30032002/Blog_Website#187]
### Contact Details

rudra888156@gmail.com

### What happened?

When switching to the dark theme, the content of the blog becomes invisible or difficult to read. This issue does not occur in light mode, where the content is clearly visible. The problem seems to be related to the text color and background contrast in the dark theme.
![image](https://github.com/user-attachments/assets/d8d3e21a-4b4a-457c-8fe8-c16c93d0c0c8)
![image](https://github.com/user-attachments/assets/de389df1-8e7b-433f-89cd-d92e2c92f5cc)

**Expected**
1.Blog content should remain visible and readable in both light and dark themes.
2.The text color should adjust appropriately based on the background color in dark mode.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rudrapratap63** [comment]
@Kritika30032002 Please assign this issue to me

**Comment by Kritika30032002** [comment]
change color UI for dark theme

**Comment by sameer-soni** [comment]
If you are not working on this issue, can I get assigned?

**Comment by rudrapratap63** [comment]
Hello @sameer-soni , i am working on this issue .

**Comment by rudrapratap63** [comment]
@Kritika30032002 , could you please review the [PR](https://github.com/Kritika30032002/Blog_Website/pull/216)?
