### ISSUE TITLE
fix sign-up and sign-in form 

### ISSUE THREAD

**Issue by MaahiVaghela** [Kritika30032002/Blog_Website#197]
there is no need of sign-in and sign-up both on navbar.  In Sign-in form a button or link to sign-up can be provided. The UI of sign-up and sign-in forms is also not proper. Please assign this to me

**Comment by dixitaditya41** [comment]
@Kritika30032002  can you please assign this task to me as it will prompt both sign up and sign in as lists and user will go with whatever way he's gonna go and it will make ui look great
