### ISSUE TITLE
Enhancement: Bold Logo & Home Link

### ISSUE THREAD

**Issue by lilmow** [Kritika30032002/Blog_Website#23]
Make the project logo bold and add a home link. When users click the logo on the "Compose" page, it should take them back to the home page.

Expected Behavior:
Clicking the logo on the "Compose" page should redirect to the home page.

This enhancement will improve the user experience. I'm ready to create a pull request once it's approved. Any specific guidelines or preferences are appreciated. Thanks!

**Comment by ashajyothi06** [comment]
@Kritika30032002 if possible assign it to me
