### ISSUE TITLE
Adding Blog detail page

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Blog_Website#27]
it should display entire blog with other details like when written, author and more

**Comment by sayumimuthu** [comment]
Hi, I'd like to know more about your expectations on this issue so that I can work on it under Hacktoberfest.

**Comment by Kritika30032002** [comment]
you can ask your doubt in discord channel

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I want to change posts into good looking blogs or cards at present they are displaying like a Paragraph .

and also I will add Update functionality to that blogs or cards  so that user can update the posts.

can you assign this  _Hacktoberfest_23 : )

**Comment by Kritika30032002** [comment]
do not add update functionality

**Comment by avinasharex** [comment]
I want to work on this issue, please assign it to me.

**Comment by YashSachan2** [comment]
@Kritika30032002 can I work on this issue under Codepeak-23.
