### ISSUE TITLE
Improve Contact-us page

### ISSUE THREAD

**Issue by Nupur19nj** [Kritika30032002/Blog_Website#29]
Hey!
I want to improve contact-us page can you please assign me this under Hacktoberfest-accepted!

**Comment by Tulsi5990** [comment]
Hey, I want to improve contact-us page. Please assign me.

**Comment by Ayush05m** [comment]
It's been 3 days since this issue has been created but not solved yet.
Assign me this task will take just a couple of hour.

**Comment by Kritika30032002** [comment]
@Nupur19nj r u working?

**Comment by Nupur19nj** [comment]
Yes almost done!

**Comment by Nupur19nj** [comment]
![image](https://github.com/Kritika30032002/Blog_Website/assets/114866308/4ea73e7d-d142-4f9a-9a08-c8b6f2acee1f)

**Comment by Nupur19nj** [comment]
hey can you please merge the PR it's been 2 days!

**Comment by Nupur19nj** [comment]
Hey! why you are not merging the PR if there's any issue tell me
