### ISSUE TITLE
Add blogs

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Blog_Website#34]
Add Blogs to the website which should be copyright free and self written.

**Comment by EternoSeeker** [comment]
Please elaborate the issue, does it refer to adding sample blogs ?

**Comment by Kritika30032002** [comment]
It includes adding original blogs (without any copyright issue). 

you can create one data.json file for this purpose.

**Comment by DeexithParand2k2** [comment]
Hi @Kritika30032002 can you assign this issue to me, I'll try to resolve. Also can you add hacktoberfest-accepted tag to this issue.

**Comment by GautamRaj-12** [comment]
Hey, I would like to work on this. One question though: If I contribute now , will it be counted in my codepeak stats? As there is no login option on codepeak, only registered and just received a mail.

**Comment by YashSachan2** [comment]
Hi @Kritika30032002  can I work on this issue under Codepeak-23

**Comment by Kritika30032002** [comment]
Content should not have any copyright issue

**Comment by YashSachan2** [comment]
@Kritika30032002 I have made a pr adding blogs with no copyright issue and a read blog button to read those blogs.Please look into it and assign me the points

**Comment by YashSachan2** [comment]
@Kritika30032002 I have made a new pr making the asked changes adding blogs with no copyright issue in blog.json and a read blog button to read those blogs.Also added the screen recording.Please look into it and assign me the points

**Comment by jinx-vi-0** [comment]
please assign this issue to me.

**Comment by alvin-dennis** [comment]
@Kritika30032002 Please assign me this issue under PHICSIT as i can add more blogs without copyright.

**Comment by timmySpark** [comment]
@alvin-dennis , can you include images in the blogs you're going to create
the new design will have a spot for images and published date

**Comment by alvin-dennis** [comment]
@timmySpark I will try to add images. Also I will not be doing the design. I will do if I have the time only

**Comment by timmySpark** [comment]
i'm already working on the design @alvin-dennis

**Comment by alvin-dennis** [comment]
@timmySpark that's great!
I will focus on adding the images then
