### ISSUE TITLE
UI Enhacement: Hover effect for navbar links

### ISSUE THREAD

**Issue by Varad0014** [Kritika30032002/Blog_Website#40]
Hey! I've got a few suggestions for hover effects on the navbar links:

https://github.com/Kritika30032002/Blog_Website/assets/77493105/e358f6ae-f0ca-4710-be55-7e5a1d0959b8

https://github.com/Kritika30032002/Blog_Website/assets/77493105/ad30a2fa-efc9-484c-ad8f-ff72a5339751

https://github.com/Kritika30032002/Blog_Website/assets/77493105/4e0a2ed7-c9af-404e-b75e-c3064415ecf0

Let me know if you're interested in any of these, and I can incorporate them into the website.

**Comment by Varad0014** [comment]
Hey @Kritika30032002, could you tell me which animation you'd prefer from the three options?

**Comment by Kritika30032002** [comment]
last one @Varad0014

**Comment by shashankk204** [comment]
Ma'am @Kritika30032002  can you assign me this issue.
