### ISSUE TITLE
create a proper logo for the website 

### ISSUE THREAD

**Issue by Kriagr23** [Kritika30032002/Blog_Website#48]
Hi, @Kritika30032002 I would like to create a proper logo for the website kindly assign this issue to me

**Comment by saurabhgdeshmukh** [comment]
@Kritika30032002 assign this task to me

**Comment by Kritika30032002** [comment]
under which program?

**Comment by saurabhgdeshmukh** [comment]
codepeak23

**Comment by AaadityaG** [comment]
Can I do it...@Kritika30032002

**Comment by Kritika30032002** [comment]
@saurabhgdeshmukh are you working on this?
