### ISSUE TITLE
feat : user profile section 

### ISSUE THREAD

**Issue by AishaAgarwal** [Kritika30032002/Blog_Website#57]
Creating a user profile section allowing users to create profile wherein they can view and edit their personal information and can also see a list of blog posts created by that specific user on their profile. 
@Kritika30032002 please assign me this issue.

**Comment by NandishM0618** [comment]
@AishaAgarwal are you working on this issue right now ?

**Comment by AishaAgarwal** [comment]
Its almost done ..just working on UI ..rest is all done
