### ISSUE TITLE
Adding Envicornment variables and developement environment

### ISSUE THREAD

**Issue by govind-kumarr** [Kritika30032002/Blog_Website#6]
Currently Port Number is hardcoded and there is no script defined to start the project.

**Comment by govind-kumarr** [comment]
@Kritika30032002  Can you this to me?

**Comment by mohammedasimahmed** [comment]
Hi @Kritika30032002 could you assign this to me

**Comment by govind-kumarr** [comment]
@mohammedasimahmed  I already opened a pull request with this issue. There is a lot of work that needs to be done.

**Comment by mohammedasimahmed** [comment]
> @mohammedasimahmed I already opened a pull request with this issue. There is a lot of work that needs to be done.

Alright
