### ISSUE TITLE
Adding Error Handling and Validation To Forms 

### ISSUE THREAD

**Issue by Ayusht777** [Kritika30032002/Blog_Website#64]
The website's has "Contact Us," "Sign Up," and "Sign In" forms lack proper error handling and validation, leading to the absence of error messages.

**Comment by Kritika30032002** [comment]
program name?

**Comment by Ayusht777** [comment]
can you assigned  codepeak Label

**Comment by Ayusht777** [comment]
can you add this link https://www.mongodb.com/try/download/community to the readme file

**Comment by Kritika30032002** [comment]
you can create a issue and pr after adding this

**Comment by YashSachan2** [comment]
@Kritika30032002 Can I work on this issue?

**Comment by Kritika30032002** [comment]
@Ayusht777  Are you working on this?

**Comment by Ayusht777** [comment]
I'm encountering installation issues with MongoDB. Could you please assign this task to someone else?

**Comment by Yash-Ainapure** [comment]
@YashSachan2  are you working on it , otherwise @Kritika30032002 please assign it to me.

**Comment by YashSachan2** [comment]
> @YashSachan2 are you working on it , otherwise @Kritika30032002 please assign it to me.

Yes bro I am working on it

**Comment by Yash-Ainapure** [comment]
> > @YashSachan2 are you working on it , otherwise @Kritika30032002 please assign it to me.
> 
> Yes bro I am working on it

Ok, no problem 😄

**Comment by YashSachan2** [comment]
@Kritika30032002 I have made the pr resolving the issue and also added some extra features.Please consider them and assign me the points under Codepeak-23
