### ISSUE TITLE
NavBar responsiveness issue 

### ISSUE THREAD

**Issue by Devesh-Daku** [Kritika30032002/Blog_Website#65]
I'd like to suggest for having a responsive nav bar for this project
 
![Blog_website](https://github.com/Kritika30032002/Blog_Website/assets/121988601/f6f69415-7ee1-4e61-a4c3-a1677c18563b)

**Comment by Devesh-Daku** [comment]
I'd like to solve this issue

**Comment by Devesh-Daku** [comment]
sorry for making changes without consulting you first. I thought it would enhance the user experience, for both mobile and desktop view

**Comment by Albert-2** [comment]
hey @Kritika30032002
I would very much like to work on this issue as I'm quite good at responsive UI's
can you please assign me the same
THANK YOU FOR CONSIDERING..... :)

**Comment by Kritika30032002** [comment]
@Devesh-Daku Are you working on this?

**Comment by Devesh-Daku** [comment]
Yes , I am travelling ill do by tomorrow evening

**Comment by Kritika30032002** [comment]
okay

**Comment by DHRUVKHANDELWAL00** [comment]
Hey @Kritika30032002 , Can i please work on it under kwoc?

**Comment by DHRUVKHANDELWAL00** [comment]
The issue is closed? @Kritika30032002
