### ISSUE TITLE
Adding a Delete button

### ISSUE THREAD

**Issue by Surajit0573** [Kritika30032002/Blog_Website#66]
There is no way to delete any created blog, so I would like to add a delete button.

![Screenshot 2023-12-09 172021](https://github.com/Kritika30032002/Blog_Website/assets/111490250/992bf399-e35b-464b-b542-0f9eb68b33ab)

**Comment by GAGANRAGHAV** [comment]
is this a codepeak issue ...please add a tag ....add please assign this to me

**Comment by Kritika30032002** [comment]
Not required as only admin should be allowed to delete who can delete from data itself
