### ISSUE TITLE
Autosave not supported

### ISSUE THREAD

**Issue by SharmaDhruv2511** [Kritika30032002/Blog_Website#70]
While running the project if there are any changes we made we have to restart the server again. We have to terminate the server again and again after making changes.

**Expected Behaviour** -

Autosave should be done using cntrl + s after every changes

**Comment by SharmaDhruv2511** [comment]
@Kritika30032002   if you can assign me this issue it would be great.

**Comment by Kritika30032002** [comment]
if I am getting your issue right then you should search of Nodemon

**Comment by SharmaDhruv2511** [comment]
Yes. Implementing nodemon will be the solution.
