### ISSUE TITLE
Navigation Menu Button

### ISSUE THREAD

**Issue by saurabhgdeshmukh** [Kritika30032002/Blog_Website#72]
I think there must be a navigation menu for small dimensions.

**Comment by Kritika30032002** [comment]
brief more

**Comment by saurabhgdeshmukh** [comment]
![image](https://github.com/Kritika30032002/Blog_Website/assets/128806572/4324d40c-c578-465e-a860-c9dac2670830)
menu option like this in mobile devices or for small screen resolution

**Comment by singhcoder694** [comment]
Can I work on this issue if @saurabhgdeshmukh is not....? @Kritika30032002

**Comment by saurabhgdeshmukh** [comment]
@Kritika30032002 why have you closed the issue I'm working on it.

**Comment by Kritika30032002** [comment]
Its been 3 days now and i don't think it takes this much time 


Hurry up and submit pr
