### ISSUE TITLE
404 page misaligned

### ISSUE THREAD

**Issue by Yash-Ainapure** [Kritika30032002/Blog_Website#85]
The 404 page not found is not aligned to center
screenshot:-
![Screenshot (129)](https://github.com/Kritika30032002/Blog_Website/assets/136250383/a8f6ecde-bc61-4bfd-8fbb-34b646cfa194)

I would like to slightly change this to a proper 404 page which looks like this :-
![Screenshot (127)](https://github.com/Kritika30032002/Blog_Website/assets/136250383/fa5e339f-a2a9-418b-b7f7-a1215c909ef2)

**Comment by Yechiel82** [comment]
claim
