### ISSUE TITLE
Improving responsiveness of overall website

### ISSUE THREAD

**Issue by drockparashar** [Kritika30032002/Blog_Website#90]
I have listed some responsiveness issues . Here are some of them:
1) 
![image](https://github.com/Kritika30032002/Blog_Website/assets/118686637/9b12549a-02b0-45f1-89ec-904012de2647)

Here the main section is much smaller in phone view.

2)
![image](https://github.com/Kritika30032002/Blog_Website/assets/118686637/f606d10c-9b1b-425d-be24-10f9ab0854ae)

Here the contents cards are not centrally aligned

3)
![image](https://github.com/Kritika30032002/Blog_Website/assets/118686637/b5199fe4-b5c4-46a7-99d0-b64efc844aaf)

The blogs in phone view are very small and viewed horizontally , they can be made into cards for better view.

**Comment by Chetax** [comment]
@drockparashar Does You Are Still Working On this issue Else i Want To Like On This Issue
