### ISSUE TITLE
[ENHANCEMENT] Forms shadow on dark mode.

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/Blog_Website#94]
In light mode, the forms in the signup, in and contact pages have great shadows as shown below.
<img width="624" alt="image" src="https://github.com/Kritika30032002/Blog_Website/assets/108126089/4c67302b-384c-4a5b-92cf-ea7ac58b10ca">
But in the dark mode its whole another story as the shadow suddenly disappears. like there is no out line on the box.
<img width="622" alt="image" src="https://github.com/Kritika30032002/Blog_Website/assets/108126089/b94acc0d-e67b-4899-a6db-ea81796de49a">

I think this issue is worth noteing.

**Comment by Kritika30032002** [comment]
program name?

**Comment by nepalivai** [comment]
Sorry!!!! can't understand what you are asking by program name.

**Comment by Kritika30032002** [comment]
codepeak or kwoc participant?

**Comment by nepalivai** [comment]
codepeak
