### ISSUE TITLE
Navabar Toggle Effect Element Are rendering On Navbar Logo

### ISSUE THREAD

**Issue by Chetax** [Kritika30032002/Blog_Website#98]
Navabar Toggle Effect Element Are rendering On Navbar Logo
![Screenshot 2023-12-28 100542](https://github.com/Kritika30032002/Blog_Website/assets/99749401/de0600f8-08c3-401d-8918-289b7e349140)

**Comment by Chetax** [comment]
@Kritika30032002 Assing Issue Under Codepeak'23 Medium

**Comment by Kritika30032002** [comment]
https://github.com/Kritika30032002/Blog_Website/pull/96

your this pr is merged now 
then how this could have raised ?
Are you spamming just to contribute more?
And easy/medium/hard I can decide don't worry about that
