### ISSUE TITLE
[BUG] Unresponsive text in signup page.

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/Blog_Website#99]
As shown in the picture below the text inside the div is not inside some text is over flowing. 
<img width="960" alt="image" src="https://github.com/Kritika30032002/Blog_Website/assets/108126089/4ad44e97-2d9b-4038-8517-6ec98dcf9a23">

**Comment by nepalivai** [comment]
Hey @Kritika30032002, Thanks for assigning me the issue but i cant seem to find where the code is located can you help me with that?

**Comment by hemantgovekar** [comment]
hi @nepalivai : Are you still working on the change?
hi @Kritika30032002 : I found the error , I can change the file if you want. Let me know?


`

**Comment by nepalivai** [comment]
hey @hemantgovekar, Nice to hear that you would like to work, I am fairly new to open-source and I want to resolve this issue by my self but i will appreciate any helping hand.

**Comment by hemantgovekar** [comment]
ya sure @nepalivai : the issue file is error.ejs. if you can figure out sure go ahead.
If not, I can help you, please fell free to ping me on hemantgovekar@gmail.com

**Comment by nepalivai** [comment]
Thanks @hemantgovekar, Got the issue fixed with your help. Really appreciate the help.

**Comment by nepalivai** [comment]
hey @Kritika30032002, have a look at this issue it was completed
